### PR TITLE
Good return values for min_time and max_time

### PR DESCRIPTION
**Pull request by iraadit**
When executing the code in Dynamic benchmarks mode (see Example 14), I had weird results for min_time and max_time.
It was because they were divided by _total_operations, like done for avg_time, but shouldn't.
I didn't try the other modes.
Correct me if I'm wrong.

### CODE REVIEW

**Comment by chronoxor** [comment]
What report did you get?

Mine is the following:
```
===============================================================================
CppBenchmark report. Version 1.0.0.0                                           
===============================================================================
CPU architecture: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz                     
CPU logical cores: 8                                                           
CPU physical cores: 4                                                          
CPU clock speed: 3.998 GHz                                                     
CPU Hyper-Threading: enabled                                                   
RAM total: 31.962 GiB                                                          
RAM free: 21.089 GiB                                                           
===============================================================================
OS version: Microsoft Windows 8 Enterprise Edition (build 9200), 64-bit        
OS bits: 64-bit                                                                
Process bits: 64-bit                                                           
Process configuration: release                                                 
Local timestamp: Tue Oct  6 17:50:48 2020                                      
UTC timestamp: Tue Oct  6 14:50:48 2020                                        
===============================================================================
Benchmark: Initialization                                                      
Attempts: 1                                                                    
Duration: 5 seconds                                                            
-------------------------------------------------------------------------------
Phase: Initialization                                                          
Total time: 2.001 s                                                            
===============================================================================
Benchmark: Calculate                                                           
Attempts: 1                                                                    
Duration: 5 seconds                                                            
-------------------------------------------------------------------------------
Phase: Calculate                                                               
Total time: 2.206 s                                                            
-------------------------------------------------------------------------------
Phase: Calculate.1                                                             
Average time: 100.731 ms/op                                                    
Minimal time: 20.020 ms/op                                                     
Maximal time: 20.195 ms/op                                                     
Total time: 503.657 ms                                                         
Total operations: 5                                                            
Operations throughput: 9 ops/s                                                 
-------------------------------------------------------------------------------
Phase: Calculate.2                                                             
Total time: 501.457 ms                                                         
-------------------------------------------------------------------------------
Phase: Calculate.2.1                                                           
Total time: 200.715 ms                                                         
-------------------------------------------------------------------------------
Phase: Calculate.2.2                                                           
Total time: 300.709 ms                                                         
-------------------------------------------------------------------------------
Phase: Calculate.3                                                             
Average time: 400.567 ms/op                                                    
Minimal time: 133.495 ms/op                                                    
Maximal time: 133.556 ms/op                                                    
Total time: 1.201 s                                                            
Total operations: 3                                                            
Operations throughput: 2 ops/s                                                 
===============================================================================
Benchmark: Cleanup                                                             
Attempts: 1                                                                    
Duration: 5 seconds                                                            
-------------------------------------------------------------------------------
Phase: Cleanup                                                                 
Total time: 1.000 s                                                            
===============================================================================
```

**Comment by iraadit** [comment]
For something similar to your Phase 3, I was getting microseconds for the min and max time, and milliseconds for average time.

In fact, it is the case in what you pasted here too:
`Phase: Calculate.3                                                             
Average time: 400.567 ms/op                                       
Minimal time: 133.495 ms/op                                              
Maximal time: 133.556 ms/op   
`
The maximal time is inferior to the average time (what is impossible)

**Comment by chronoxor** [comment]
Aaah now I see. We'll look into it more deeply soon.

**Comment by chronoxor** [comment]
Fixed

**Pull request closed without merging**
